routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------------------------------------------------------------------
| Auth && Passwords
'------------------------------------------------------------------------------*/
Route::get('login', '\App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
Route::post('login', '\App\Http\Controllers\Auth\LoginController@login');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
Route::group(['prefix' => 'password'], function () {
    Route::post('email', '\App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('reset', '\App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('reset', '\App\Http\Controllers\Auth\ResetPasswordController@reset');
    Route::get('reset/{token}', '\App\Http\Controllers\Auth\ResetPasswordController@showResetForm')->name('password.reset');
});

/*------------------------------------------------------------------------------
| App
'------------------------------------------------------------------------------*/
Route::group(['middleware' => 'auth'], function () {
    Route::get('', 'ScreenController');
    Route::post('screens/{action}', 'ScreenActionController')->where('action', 'videos|orientation|reboot');
    Route::resource('screens', 'ScreenController', ['only' => ['index', 'store', 'update', 'destroy']]);

    Route::get('videos/{video}/stream', 'VideoController@stream');
    Route::get('videos/{video}/download', 'VideoController@download');
    Route::resource('videos', 'VideoController', ['only' => ['index', 'store', 'update', 'destroy']]);

    Route::resource('users/profile', 'ProfileController', ['only' => ['index', 'update']]);
    Route::resource('users', 'UserController', ['only' => ['index', 'store', 'update', 'destroy']]);
});

resources/views/partials/empty.blade.php
<template slot="empty">
    <section class="section">
        <div class="content has-text-grey has-text-centered">
            <p>
                <b-icon icon="emoticon-sad" size="is-large"></b-icon>
            </p>
            <p>{{ $slot }}</p>
        </div>
    </section>
</template>

resources/views/partials/filters.blade.php
<div class="columns is-mobile is-multiline">
    @if($pagination ?? true)
        <div class="column is-12-mobile is-narrow">
            <b-field horizontal label="Mostrar:">
                <b-select v-model="query.perPage" @input="all()">
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="250">250</option>
                </b-select>
            </b-field>
        </div>
    @endif
    <div class="column is-12-mobile">
        <b-field expanded>
            <b-input type="text" placeholder="Buscar..." icon="magnify" v-model="query.search" @keyup.native.enter="all()" expanded></b-input>
        </b-field>
    </div>
</div>

resources/views/partials/navbar.blade.php
<nav class="navbar is-transparent">
    <div class="navbar-brand">
        <a class="navbar-item" href="{{ route('screens.index') }}">
            {{ config('app.name') }}
        </a>
        @auth
            <button type="button" class="navbar-burger button is-white" :class="{ 'is-active': isActive }" @click="isActive = !isActive">
                <span></span>
                <span></span>
                <span></span>
            </button>
        @endauth
    </div>

    @auth
        <div class="navbar-menu" :class="{ 'is-active': isActive }">
            <div class="navbar-end">
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">{{ auth()->user()->name }}</a>
                    <div class="navbar-dropdown is-boxed is-right">
                        <a class="navbar-item @active('screens.index')" href="{{ route('screens.index') }}">Pantallas</a>
                        @if(auth()->user()->isClient())
                            <a class="navbar-item @active('videos.index')" href="{{ route('videos.index') }}">Videos</a>
                        @endif
                        @if(auth()->user()->isAdmin())
                            <a class="navbar-item @active('users.index')" href="{{ route('users.index') }}">Usuarios</a>
                        @endif
                        <a class="navbar-item @active('profile.index')" href="{{ route('profile.index') }}">Perfil</a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{{ route('logout') }}">Salir</a>
                    </div>
                </div>
            </div>
        </div>
    @endauth
</nav>